services:
  app:
    build: .
    container_name: gRPC_auth
    restart: unless-stopped


    env_file:
      - src/.env

    environment:
      # ✅ This overrides or provides the DB URL for Alembic / SQLAlchemy
      DATABASE_URL: postgresql+asyncpg://bekzod:123@postgres:5432/auth


    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bekzod
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bekzod"]
      interval: 10s
      timeout: 5s
      retries: 5
