"""Change full tablems

Revision ID: cdf3ddc47d8f
Revises: 9eb4fcbbfd4a
Create Date: 2025-10-07 13:40:25.779091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf3ddc47d8f'
down_revision: Union[str, Sequence[str], None] = '9eb4fcbbfd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
